name: Image Resize and Evaluation

on:
  push:
    branches:
      - feature/image_resize

jobs:
  evaluate_images:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: pip install scikit-learn scikit-image

    - name: Run Image Resizing and Evaluation
      run: python resize_and_evaluate.py
